### PR TITLE
Bump dependencies to 7

### PR DESCRIPTION
**Pull request by einarmo**
Projects are running into conflicts due to .NET 7 dependencies.

### CODE REVIEW

**Comment by dbrattli** [comment]
I'm a bit worried that this will force all dependents to .NET 7. What we need is something like e.g `nuget FSharp.Core >= 6.0.0 lowest_matching: true` so we generate a `>=` dependency in the lock file.

**Comment by einarmo** [comment]
> I'm a bit worried that this will force all dependents to .NET 7. What we need is something like e.g `nuget FSharp.Core >= 6.0.0 lowest_matching: true` so we generate a `>=` dependency in the lock file.

It couldn't possibly, right? This library is built for .NET standard, we wouldn't be able to build it at all if the dependencies required .NET 7.

**Comment by dbrattli** [comment]
dependents (down stream), not dependencies (up stream)

**Comment by einarmo** [comment]
> dependents (down stream), not dependencies (up stream)

My comment was a bit unclear, I think. If dependencies required .NET 7, Oryx would not compile for .NET standard, which is compatible with .NET Core 3 and .NET framework 4. If Oryx compiles at all, any dependents would be able to run any version of .NET that is compatible with .NET Standard 2.0.

**Comment by xperiandri** [comment]
Maybe you will get rid of Paketand do muti-targeting?

**Comment by xperiandri** [comment]
I have a lot of annoying warnings because of weird Paket version locks

**Comment by einarmo** [comment]
I'm fairly confident this will be fine, the PI and PI AF extractors are running 7.0 versions of several core packages, and they are built for .NET framework. I don't see how this bump to 7 is any different from the previous versions, which were 6.

**Review by xperiandri — APPROVED** [review]

**Review by dbrattli — APPROVED** [review]
Let's try this

**Pull request merged**
