### PR TITLE
Refactor response to include response headers and status code

### PR DESCRIPTION
**Pull request by dbrattli**
Refactor response type from `'T` to `HttpResponse<'T>` to it can preserve the response headers and status code. This is important when using Oryx for e.g a web proxy where you want to forward headers upstream.

### CODE REVIEW

**Review by polomani — APPROVED** [review]

**Review by polomani — COMMENTED** [review]
would it be an option to split this pr into two, so we can see what the actual changes are?
and then reformat in another PR?

**Comment by dbrattli** [comment]
It looks a bit ugly but the main change is really just:

```fs
type Context<'T> =
     {
         Request: HttpRequest
         Response: 'T
     }
```

to

```fs
type Context<'T> =
     {
         Request: HttpRequest
         Response: HttpResponse<'T>
     }
```

Where `HttpResponse` is:

```fs
type HttpResponse<'T> =
    {
        /// Response content
        Content: 'T
        /// Map of received headers
        Headers: Map<string, seq<string>>
        /// Http status code
        StatusCode: HttpStatusCode
        /// True if response is successful
        IsSuccessStatusCode: bool
        ReasonPhrase: string
    }
```

Then the rest of the changes is just to adjust for this change.

**Comment by dbrattli** [comment]
Formatting only PR: https://github.com/cognitedata/oryx/pull/62/files

**Review by tengelskar — APPROVED** [review]
Looks good!

**Pull request merged**
